name: Test ansibug
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: |
            pyproject.toml

      - name: Testing
        shell: bash
        run: |
          set -ex

          python -m pip install tox

          tox -f py312 ansible_devel
